# Generated by Django 5.2.3 on 2025-06-24 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_projects_director'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='foto',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='users/fotos', verbose_name='Foto'),
        ),
    ]
