# Generated by Django 5.2.3 on 2025-06-24 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_projects_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='foto',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='projects/fotos', verbose_name='Foto'),
        ),
    ]
