# Generated by Django 5.2.3 on 2025-06-25 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('gender', models.SmallIntegerField(choices=[(0, 'Masculino'), (1, 'Feminino'), (2, 'Outro')], verbose_name='Gender')),
                ('voice_type', models.SmallIntegerField(choices=[(0, 'Normal'), (1, 'Infantil'), (2, 'Robô'), (3, 'Vilão')], default=0, verbose_name='Voice type')),
                ('description', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, default=None, null=True, upload_to='characters/fotos', verbose_name='Foto')),
            ],
        ),
    ]
