# Generated by Django 5.2.3 on 2025-06-25 00:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='news/media/')),
                ('caption', models.CharField(blank=True, max_length=255, null=True)),
                ('news_type', models.IntegerField(default=0)),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='news.news')),
            ],
            options={
                'verbose_name': 'News Media',
                'verbose_name_plural': 'News Media',
                'db_table': 'news_media',
            },
        ),
    ]
